export const SKILL_ALIASES: Record<string, string> = {
  // data Science, ai & ml
  ml: "machine learning",
  ai: "artificial intelligence",
  dl: "deep learning",
  nlp: "natural language processing",
  cv: "computer vision",
  llm: "large language models",
  nn: "neural networks",
  cnn: "convolutional neural networks",
  rnn: "recurrent neural networks",
  rl: "reinforcement learning",
  genai: "generative ai",
  ds: "data science",
  da: "data analysis",
  de: "data engineering",

  // web & frontend
  js: "javascript",
  ts: "typescript",
  react: "reactjs",
  "react.js": "reactjs",
  node: "nodejs",
  "node.js": "nodejs",
  vue: "vuejs",
  "vue.js": "vuejs",
  ng: "angular",
  angularjs: "angular",
  html: "hypertext markup language",
  css: "cascading style sheets",
  ui: "user interface",
  ux: "user experience",
  "ui/ux": "user interface / user experience",
  a11y: "accessibility",
  i18n: "internationalization",
  l10n: "localization",

  // cloud & devOps
  k8s: "kubernetes",
  aws: "amazon web services",
  gcp: "google cloud",
  "google cloud platform": "google cloud",
  azure: "microsoft azure",
  ci: "continuous integration",
  cd: "continuous deployment",
  "ci/cd": "continuous integration and continuous deployment",
  cicd: "continuous integration and continuous deployment",
  iac: "infrastructure as code",
  vm: "virtual machine",
  ecs: "elastic container service",
  eks: "elastic kubernetes service",
  s3: "simple storage service",

  // database & backend
  db: "database",
  dba: "database administration",
  sql: "structured query language",
  nosql: "not only sql",
  rdbms: "relational database management system",
  pg: "postgresql",
  postgres: "postgresql",
  mongo: "mongodb",
  api: "application programming interface",
  rest: "representational state transfer",
  graphql: "gql",
  gql: "graphql",

  // methodologies & general tools
  agile: "agile methodology",
  qa: "quality assurance",
  tdd: "test driven development",
  bdd: "behavior driven development",
  oop: "object oriented programming",
  fp: "functional programming",
  os: "operating system",
  vcs: "version control system",
  mr: "merge request",

  // management & hr
  pm: "project management",
  pmp: "project management professional",
  csm: "certified scrum master",
  hr: "human resources",
  b2b: "business to business",
  b2c: "business to consumer",
  crm: "customer relationship management",
  erp: "enterprise resource planning",
  mba: "master of business administration",
  roi: "return on investment",
  kpi: "key performance indicator",
  okr: "objectives and key results",
  coo: "chief operating officer",
  ceo: "chief executive officer",
  cfo: "chief financial officer",
  cto: "chief technology officer",
  cmo: "chief marketing officer",

  // finance & accounting
  cpa: "certified public accountant",
  cfa: "chartered financial analyst",
  "p&l": "profit and loss",
  ap: "accounts payable",
  ar: "accounts receivable",

  // healthcare & medical
  cpr: "cardiopulmonary resuscitation",
  rn: "registered nurse",
  lpn: "licensed practical nurse",
  md: "medical doctor",
  emr: "electronic medical records",
  ehr: "electronic health records",
  hipaa: "health insurance portability and accountability act",

  // marketing & sales
  sem: "search engine marketing",
  seo: "search engine optimization",
  smm: "social media marketing",
  ppc: "pay per click",
  cta: "call to action",
};
